# Generated by Django 4.2 on 2023-05-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
