# Generated by Django 4.2 on 2023-05-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Name', models.CharField(max_length=200)),
                ('Ratings', models.FloatField()),
                ('Year_Of_Release', models.IntegerField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
